#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# recreate.tcl: Tcl script for re-creating project 'ad7606x_fmc_zed'
#
# Generated by Vivado on Tue Feb 24 10:31:52 CET 2026
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (recreate.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/madi1/_GIT/irs-systems/ADI-hdl/projects/ad7606x_fmc/zed/INTF0_ADCNBITS18/ad7606x_fmc_zed.srcs/sources_1/imports/hdl/system_wrapper.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/madi1/_GIT/irs-systems/ADI-hdl/library/common/ad_edge_detect.v"
#    "/home/madi1/_GIT/irs-systems/ADI-hdl/library/util_cdc/sync_bits.v"
#    "/home/madi1/_GIT/irs-systems/ADI-hdl/library/common/ad_iobuf.v"
#    "/home/madi1/_GIT/irs-systems/ADI-hdl/projects/ad7606x_fmc/zed/system_top_pi.v"
#    "/home/madi1/_GIT/irs-systems/ADI-hdl/projects/common/zed/zed_system_constr.xdc"
#    "/home/madi1/_GIT/irs-systems/ADI-hdl/projects/ad7606x_fmc/zed/system_constr_pif.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/ad7606x_fmc_zed.srcs/sources_1/imports/hdl/system_wrapper.v"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  set files [list \
 "[file normalize "$origin_dir/../../../../library/common/ad_edge_detect.v"]"\
 "[file normalize "$origin_dir/../../../../library/util_cdc/sync_bits.v"]"\
 "[file normalize "$origin_dir/../../../../library/common/ad_iobuf.v"]"\
 "[file normalize "$origin_dir/../system_top_pi.v"]"\
 "[file normalize "$origin_dir/../../../common/zed/zed_system_constr.xdc"]"\
 "[file normalize "$origin_dir/../system_constr_pif.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  set paths [list \
 "[file normalize "$origin_dir/[file normalize "$origin_dir/../../../../library"]"]"\
  ]
  foreach ipath $paths {
    if { ![file isdirectory $ipath] } {
      puts " Could not access $ipath "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "ad7606x_fmc_zed"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "recreate.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
set_msg_config  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING}  -ruleid {1}  -source 2
set_msg_config  -id {Designutils 20-3303}  -string {{HDPYFinalizeIO}}  -new_severity {INFO}  -ruleid {10}  -source 2
set_msg_config  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING}  -ruleid {11}  -source 2
set_msg_config  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING}  -ruleid {12}  -source 2
set_msg_config  -id {BD 41-1343}  -new_severity {WARNING}  -ruleid {2}  -source 2
set_msg_config  -id {BD 41-1306}  -new_severity {WARNING}  -ruleid {3}  -source 2
set_msg_config  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR}  -ruleid {4}  -source 2
set_msg_config  -id {IP_Flow 19-3656}  -new_severity {INFO}  -ruleid {5}  -source 2
set_msg_config  -id {IP_Flow 19-4623}  -new_severity {INFO}  -ruleid {6}  -source 2
set_msg_config  -id {IP_Flow 19-459}  -new_severity {INFO}  -ruleid {7}  -source 2
set_msg_config  -id {Synth 8-3331}  -new_severity {INFO}  -ruleid {8}  -source 2
set_msg_config  -id {Synth 8-2490}  -new_severity {WARNING}  -ruleid {9}  -source 2


# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "/home/madi1/_GIT/irs-systems/ADI-hdl/ipcache" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "use_inline_hdl_ip" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/../../../../library"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../../../../library/common/ad_edge_detect.v"] \
 [file normalize "${origin_dir}/../../../../library/util_cdc/sync_bits.v"] \
 [file normalize "${origin_dir}/../../../../library/common/ad_iobuf.v"] \
 [file normalize "${origin_dir}/../system_top_pi.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/ad7606x_fmc_zed.srcs/sources_1/imports/hdl/system_wrapper.v"]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sources_1 $f]
}

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "generic" -value "INTF=0 NUM_OF_SDI=2 ADC_N_BITS=18" -objects $obj
set_property -name "top" -value "system_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "vhdl_generic" -value "INTF=0 NUM_OF_SDI=2 ADC_N_BITS=18" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../../../common/zed/zed_system_constr.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../../../common/zed/zed_system_constr.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../system_constr_pif.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/../system_constr_pif.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7z020clg484-1" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "system_top" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added


# Proc to create BD system
proc cr_bd_system { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name system

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:processing_system7:5.5\
  xilinx.com:ip:axi_iic:2.1\
  analog.com:user:util_i2c_mixer:1.0\
  xilinx.com:inline_hdl:ilconcat:1.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:inline_hdl:ilvector_logic:1.0\
  analog.com:user:axi_clkgen:1.0\
  analog.com:user:axi_hdmi_tx:1.0\
  analog.com:user:axi_dmac:1.0\
  xilinx.com:ip:clk_wiz:6.0\
  analog.com:user:axi_spdif_tx:1.0\
  analog.com:user:axi_i2s_adi:1.0\
  analog.com:user:axi_sysid:1.0\
  analog.com:user:sysid_rom:1.0\
  xilinx.com:inline_hdl:ilconstant:1.0\
  analog.com:user:axi_pwm_gen:1.0\
  analog.com:user:axi_ad7606x:1.0\
  analog.com:user:util_cpack2:1.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set ddr [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 ddr ]

  set fixed_io [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 fixed_io ]

  set iic_fmc [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:iic_rtl:1.0 iic_fmc ]

  set i2s [ create_bd_intf_port -mode Master -vlnv analog.com:interface:i2s_rtl:1.0 i2s ]


  # Create ports
  set spi0_csn_2_o [ create_bd_port -dir O spi0_csn_2_o ]
  set spi0_csn_1_o [ create_bd_port -dir O spi0_csn_1_o ]
  set spi0_csn_0_o [ create_bd_port -dir O spi0_csn_0_o ]
  set spi0_csn_i [ create_bd_port -dir I spi0_csn_i ]
  set spi0_clk_i [ create_bd_port -dir I spi0_clk_i ]
  set spi0_clk_o [ create_bd_port -dir O spi0_clk_o ]
  set spi0_sdo_i [ create_bd_port -dir I spi0_sdo_i ]
  set spi0_sdo_o [ create_bd_port -dir O spi0_sdo_o ]
  set spi0_sdi_i [ create_bd_port -dir I spi0_sdi_i ]
  set spi1_csn_2_o [ create_bd_port -dir O spi1_csn_2_o ]
  set spi1_csn_1_o [ create_bd_port -dir O spi1_csn_1_o ]
  set spi1_csn_0_o [ create_bd_port -dir O spi1_csn_0_o ]
  set spi1_csn_i [ create_bd_port -dir I spi1_csn_i ]
  set spi1_clk_i [ create_bd_port -dir I spi1_clk_i ]
  set spi1_clk_o [ create_bd_port -dir O spi1_clk_o ]
  set spi1_sdo_i [ create_bd_port -dir I spi1_sdo_i ]
  set spi1_sdo_o [ create_bd_port -dir O spi1_sdo_o ]
  set spi1_sdi_i [ create_bd_port -dir I spi1_sdi_i ]
  set gpio_i [ create_bd_port -dir I -from 63 -to 0 gpio_i ]
  set gpio_o [ create_bd_port -dir O -from 63 -to 0 gpio_o ]
  set gpio_t [ create_bd_port -dir O -from 63 -to 0 gpio_t ]
  set hdmi_out_clk [ create_bd_port -dir O hdmi_out_clk ]
  set hdmi_hsync [ create_bd_port -dir O hdmi_hsync ]
  set hdmi_vsync [ create_bd_port -dir O hdmi_vsync ]
  set hdmi_data_e [ create_bd_port -dir O hdmi_data_e ]
  set hdmi_data [ create_bd_port -dir O -from 15 -to 0 hdmi_data ]
  set i2s_mclk [ create_bd_port -dir O -type clk i2s_mclk ]
  set iic_mux_scl_i [ create_bd_port -dir I -from 1 -to 0 iic_mux_scl_i ]
  set iic_mux_scl_o [ create_bd_port -dir O -from 1 -to 0 iic_mux_scl_o ]
  set iic_mux_scl_t [ create_bd_port -dir O iic_mux_scl_t ]
  set iic_mux_sda_i [ create_bd_port -dir I -from 1 -to 0 iic_mux_sda_i ]
  set iic_mux_sda_o [ create_bd_port -dir O -from 1 -to 0 iic_mux_sda_o ]
  set iic_mux_sda_t [ create_bd_port -dir O iic_mux_sda_t ]
  set otg_vbusoc [ create_bd_port -dir I otg_vbusoc ]
  set spdif [ create_bd_port -dir O spdif ]
  set rx_busy [ create_bd_port -dir I rx_busy ]
  set rx_cnvst_n [ create_bd_port -dir O rx_cnvst_n ]
  set rx_db_o [ create_bd_port -dir O -from 15 -to 0 rx_db_o ]
  set rx_db_i [ create_bd_port -dir I -from 15 -to 0 rx_db_i ]
  set rx_db_t [ create_bd_port -dir O rx_db_t ]
  set rx_rd_n [ create_bd_port -dir O rx_rd_n ]
  set rx_wr_n [ create_bd_port -dir O rx_wr_n ]
  set rx_cs_n [ create_bd_port -dir O rx_cs_n ]
  set rx_first_data [ create_bd_port -dir I rx_first_data ]

  # Create instance: sys_ps7, and set properties
  set sys_ps7 [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 sys_ps7 ]
  set_property -dict [list \
    CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {666.666687} \
    CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.158730} \
    CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {125.000000} \
    CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {100.000000} \
    CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {50.000000} \
    CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
    CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {166.666672} \
    CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_ACT_TTC_PERIPHERAL_FREQMHZ {50} \
    CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {50.000000} \
    CONFIG.PCW_ACT_USB0_PERIPHERAL_FREQMHZ {60} \
    CONFIG.PCW_ACT_USB1_PERIPHERAL_FREQMHZ {60} \
    CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {111.111115} \
    CONFIG.PCW_APU_CLK_RATIO_ENABLE {6:2:1} \
    CONFIG.PCW_APU_PERIPHERAL_FREQMHZ {666.666667} \
    CONFIG.PCW_CAN0_PERIPHERAL_CLKSRC {External} \
    CONFIG.PCW_CAN0_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_CAN1_PERIPHERAL_CLKSRC {External} \
    CONFIG.PCW_CAN1_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_CAN_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_CAN_PERIPHERAL_VALID {0} \
    CONFIG.PCW_CLK0_FREQ {100000000} \
    CONFIG.PCW_CLK1_FREQ {200000000} \
    CONFIG.PCW_CLK2_FREQ {10000000} \
    CONFIG.PCW_CLK3_FREQ {10000000} \
    CONFIG.PCW_CPU_CPU_6X4X_MAX_RANGE {667} \
    CONFIG.PCW_CPU_PERIPHERAL_CLKSRC {ARM PLL} \
    CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ {33.333333} \
    CONFIG.PCW_DCI_PERIPHERAL_CLKSRC {DDR PLL} \
    CONFIG.PCW_DCI_PERIPHERAL_FREQMHZ {10.159} \
    CONFIG.PCW_DDR_PERIPHERAL_CLKSRC {DDR PLL} \
    CONFIG.PCW_DDR_RAM_HIGHADDR {0x1FFFFFFF} \
    CONFIG.PCW_ENET0_ENET0_IO {MIO 16 .. 27} \
    CONFIG.PCW_ENET0_GRP_MDIO_ENABLE {1} \
    CONFIG.PCW_ENET0_GRP_MDIO_IO {MIO 52 .. 53} \
    CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} \
    CONFIG.PCW_ENET0_RESET_ENABLE {0} \
    CONFIG.PCW_ENET1_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_ENET1_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_ENET_RESET_ENABLE {1} \
    CONFIG.PCW_ENET_RESET_POLARITY {Active Low} \
    CONFIG.PCW_ENET_RESET_SELECT {Share reset pin} \
    CONFIG.PCW_EN_4K_TIMER {0} \
    CONFIG.PCW_EN_CAN0 {0} \
    CONFIG.PCW_EN_CAN1 {0} \
    CONFIG.PCW_EN_CLK0_PORT {1} \
    CONFIG.PCW_EN_CLK1_PORT {1} \
    CONFIG.PCW_EN_CLK2_PORT {0} \
    CONFIG.PCW_EN_CLK3_PORT {0} \
    CONFIG.PCW_EN_DDR {1} \
    CONFIG.PCW_EN_EMIO_CAN0 {0} \
    CONFIG.PCW_EN_EMIO_CAN1 {0} \
    CONFIG.PCW_EN_EMIO_CD_SDIO0 {0} \
    CONFIG.PCW_EN_EMIO_CD_SDIO1 {0} \
    CONFIG.PCW_EN_EMIO_ENET0 {0} \
    CONFIG.PCW_EN_EMIO_ENET1 {0} \
    CONFIG.PCW_EN_EMIO_GPIO {1} \
    CONFIG.PCW_EN_EMIO_I2C0 {0} \
    CONFIG.PCW_EN_EMIO_I2C1 {0} \
    CONFIG.PCW_EN_EMIO_MODEM_UART0 {0} \
    CONFIG.PCW_EN_EMIO_MODEM_UART1 {0} \
    CONFIG.PCW_EN_EMIO_PJTAG {0} \
    CONFIG.PCW_EN_EMIO_SDIO0 {0} \
    CONFIG.PCW_EN_EMIO_SDIO1 {0} \
    CONFIG.PCW_EN_EMIO_SPI0 {1} \
    CONFIG.PCW_EN_EMIO_SPI1 {1} \
    CONFIG.PCW_EN_EMIO_SRAM_INT {0} \
    CONFIG.PCW_EN_EMIO_TRACE {0} \
    CONFIG.PCW_EN_EMIO_TTC0 {0} \
    CONFIG.PCW_EN_EMIO_TTC1 {0} \
    CONFIG.PCW_EN_EMIO_UART0 {0} \
    CONFIG.PCW_EN_EMIO_UART1 {0} \
    CONFIG.PCW_EN_EMIO_WDT {0} \
    CONFIG.PCW_EN_EMIO_WP_SDIO0 {0} \
    CONFIG.PCW_EN_EMIO_WP_SDIO1 {0} \
    CONFIG.PCW_EN_ENET0 {1} \
    CONFIG.PCW_EN_ENET1 {0} \
    CONFIG.PCW_EN_GPIO {1} \
    CONFIG.PCW_EN_I2C0 {0} \
    CONFIG.PCW_EN_I2C1 {0} \
    CONFIG.PCW_EN_MODEM_UART0 {0} \
    CONFIG.PCW_EN_MODEM_UART1 {0} \
    CONFIG.PCW_EN_PJTAG {0} \
    CONFIG.PCW_EN_QSPI {1} \
    CONFIG.PCW_EN_RST1_PORT {1} \
    CONFIG.PCW_EN_SDIO0 {1} \
    CONFIG.PCW_EN_SDIO1 {0} \
    CONFIG.PCW_EN_SMC {0} \
    CONFIG.PCW_EN_SPI0 {1} \
    CONFIG.PCW_EN_SPI1 {1} \
    CONFIG.PCW_EN_TRACE {0} \
    CONFIG.PCW_EN_TTC0 {0} \
    CONFIG.PCW_EN_TTC1 {0} \
    CONFIG.PCW_EN_UART0 {0} \
    CONFIG.PCW_EN_UART1 {1} \
    CONFIG.PCW_EN_USB0 {1} \
    CONFIG.PCW_EN_USB1 {0} \
    CONFIG.PCW_EN_WDT {0} \
    CONFIG.PCW_FCLK0_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FCLK1_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FCLK2_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FCLK3_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_FCLK_CLK0_BUF {TRUE} \
    CONFIG.PCW_FCLK_CLK1_BUF {TRUE} \
    CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {100.0} \
    CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {200.0} \
    CONFIG.PCW_FPGA2_PERIPHERAL_FREQMHZ {50.000000} \
    CONFIG.PCW_FPGA3_PERIPHERAL_FREQMHZ {50} \
    CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
    CONFIG.PCW_FPGA_FCLK1_ENABLE {1} \
    CONFIG.PCW_GPIO_EMIO_GPIO_ENABLE {1} \
    CONFIG.PCW_GPIO_EMIO_GPIO_IO {64} \
    CONFIG.PCW_GPIO_EMIO_GPIO_WIDTH {64} \
    CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {1} \
    CONFIG.PCW_GPIO_MIO_GPIO_IO {MIO} \
    CONFIG.PCW_GPIO_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_I2C0_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_I2C1_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_I2C_RESET_ENABLE {1} \
    CONFIG.PCW_I2C_RESET_POLARITY {Active Low} \
    CONFIG.PCW_IMPORT_BOARD_PRESET {ZedBoard} \
    CONFIG.PCW_IRQ_F2P_INTR {1} \
    CONFIG.PCW_IRQ_F2P_MODE {REVERSE} \
    CONFIG.PCW_MIO_0_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_0_PULLUP {disabled} \
    CONFIG.PCW_MIO_0_SLEW {slow} \
    CONFIG.PCW_MIO_10_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_10_PULLUP {disabled} \
    CONFIG.PCW_MIO_10_SLEW {slow} \
    CONFIG.PCW_MIO_11_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_11_PULLUP {disabled} \
    CONFIG.PCW_MIO_11_SLEW {slow} \
    CONFIG.PCW_MIO_12_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_12_PULLUP {disabled} \
    CONFIG.PCW_MIO_12_SLEW {slow} \
    CONFIG.PCW_MIO_13_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_13_PULLUP {disabled} \
    CONFIG.PCW_MIO_13_SLEW {slow} \
    CONFIG.PCW_MIO_14_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_14_PULLUP {disabled} \
    CONFIG.PCW_MIO_14_SLEW {slow} \
    CONFIG.PCW_MIO_15_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_15_PULLUP {disabled} \
    CONFIG.PCW_MIO_15_SLEW {slow} \
    CONFIG.PCW_MIO_16_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_16_PULLUP {disabled} \
    CONFIG.PCW_MIO_16_SLEW {fast} \
    CONFIG.PCW_MIO_17_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_17_PULLUP {disabled} \
    CONFIG.PCW_MIO_17_SLEW {fast} \
    CONFIG.PCW_MIO_18_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_18_PULLUP {disabled} \
    CONFIG.PCW_MIO_18_SLEW {fast} \
    CONFIG.PCW_MIO_19_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_19_PULLUP {disabled} \
    CONFIG.PCW_MIO_19_SLEW {fast} \
    CONFIG.PCW_MIO_1_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_1_PULLUP {disabled} \
    CONFIG.PCW_MIO_1_SLEW {fast} \
    CONFIG.PCW_MIO_20_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_20_PULLUP {disabled} \
    CONFIG.PCW_MIO_20_SLEW {fast} \
    CONFIG.PCW_MIO_21_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_21_PULLUP {disabled} \
    CONFIG.PCW_MIO_21_SLEW {fast} \
    CONFIG.PCW_MIO_22_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_22_PULLUP {disabled} \
    CONFIG.PCW_MIO_22_SLEW {fast} \
    CONFIG.PCW_MIO_23_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_23_PULLUP {disabled} \
    CONFIG.PCW_MIO_23_SLEW {fast} \
    CONFIG.PCW_MIO_24_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_24_PULLUP {disabled} \
    CONFIG.PCW_MIO_24_SLEW {fast} \
    CONFIG.PCW_MIO_25_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_25_PULLUP {disabled} \
    CONFIG.PCW_MIO_25_SLEW {fast} \
    CONFIG.PCW_MIO_26_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_26_PULLUP {disabled} \
    CONFIG.PCW_MIO_26_SLEW {fast} \
    CONFIG.PCW_MIO_27_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_27_PULLUP {disabled} \
    CONFIG.PCW_MIO_27_SLEW {fast} \
    CONFIG.PCW_MIO_28_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_28_PULLUP {disabled} \
    CONFIG.PCW_MIO_28_SLEW {fast} \
    CONFIG.PCW_MIO_29_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_29_PULLUP {disabled} \
    CONFIG.PCW_MIO_29_SLEW {fast} \
    CONFIG.PCW_MIO_2_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_2_SLEW {fast} \
    CONFIG.PCW_MIO_30_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_30_PULLUP {disabled} \
    CONFIG.PCW_MIO_30_SLEW {fast} \
    CONFIG.PCW_MIO_31_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_31_PULLUP {disabled} \
    CONFIG.PCW_MIO_31_SLEW {fast} \
    CONFIG.PCW_MIO_32_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_32_PULLUP {disabled} \
    CONFIG.PCW_MIO_32_SLEW {fast} \
    CONFIG.PCW_MIO_33_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_33_PULLUP {disabled} \
    CONFIG.PCW_MIO_33_SLEW {fast} \
    CONFIG.PCW_MIO_34_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_34_PULLUP {disabled} \
    CONFIG.PCW_MIO_34_SLEW {fast} \
    CONFIG.PCW_MIO_35_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_35_PULLUP {disabled} \
    CONFIG.PCW_MIO_35_SLEW {fast} \
    CONFIG.PCW_MIO_36_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_36_PULLUP {disabled} \
    CONFIG.PCW_MIO_36_SLEW {fast} \
    CONFIG.PCW_MIO_37_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_37_PULLUP {disabled} \
    CONFIG.PCW_MIO_37_SLEW {fast} \
    CONFIG.PCW_MIO_38_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_38_PULLUP {disabled} \
    CONFIG.PCW_MIO_38_SLEW {fast} \
    CONFIG.PCW_MIO_39_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_39_PULLUP {disabled} \
    CONFIG.PCW_MIO_39_SLEW {fast} \
    CONFIG.PCW_MIO_3_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_3_SLEW {fast} \
    CONFIG.PCW_MIO_40_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_40_PULLUP {disabled} \
    CONFIG.PCW_MIO_40_SLEW {fast} \
    CONFIG.PCW_MIO_41_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_41_PULLUP {disabled} \
    CONFIG.PCW_MIO_41_SLEW {fast} \
    CONFIG.PCW_MIO_42_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_42_PULLUP {disabled} \
    CONFIG.PCW_MIO_42_SLEW {fast} \
    CONFIG.PCW_MIO_43_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_43_PULLUP {disabled} \
    CONFIG.PCW_MIO_43_SLEW {fast} \
    CONFIG.PCW_MIO_44_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_44_PULLUP {disabled} \
    CONFIG.PCW_MIO_44_SLEW {fast} \
    CONFIG.PCW_MIO_45_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_45_PULLUP {disabled} \
    CONFIG.PCW_MIO_45_SLEW {fast} \
    CONFIG.PCW_MIO_46_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_46_PULLUP {disabled} \
    CONFIG.PCW_MIO_46_SLEW {slow} \
    CONFIG.PCW_MIO_47_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_47_PULLUP {disabled} \
    CONFIG.PCW_MIO_47_SLEW {slow} \
    CONFIG.PCW_MIO_48_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_48_PULLUP {disabled} \
    CONFIG.PCW_MIO_48_SLEW {slow} \
    CONFIG.PCW_MIO_49_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_49_PULLUP {disabled} \
    CONFIG.PCW_MIO_49_SLEW {slow} \
    CONFIG.PCW_MIO_4_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_4_SLEW {fast} \
    CONFIG.PCW_MIO_50_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_50_PULLUP {disabled} \
    CONFIG.PCW_MIO_50_SLEW {slow} \
    CONFIG.PCW_MIO_51_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_51_PULLUP {disabled} \
    CONFIG.PCW_MIO_51_SLEW {slow} \
    CONFIG.PCW_MIO_52_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_52_PULLUP {disabled} \
    CONFIG.PCW_MIO_52_SLEW {slow} \
    CONFIG.PCW_MIO_53_IOTYPE {LVCMOS 1.8V} \
    CONFIG.PCW_MIO_53_PULLUP {disabled} \
    CONFIG.PCW_MIO_53_SLEW {slow} \
    CONFIG.PCW_MIO_5_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_5_SLEW {fast} \
    CONFIG.PCW_MIO_6_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_6_SLEW {fast} \
    CONFIG.PCW_MIO_7_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_7_SLEW {slow} \
    CONFIG.PCW_MIO_8_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_8_SLEW {fast} \
    CONFIG.PCW_MIO_9_IOTYPE {LVCMOS 3.3V} \
    CONFIG.PCW_MIO_9_PULLUP {disabled} \
    CONFIG.PCW_MIO_9_SLEW {slow} \
    CONFIG.PCW_MIO_TREE_PERIPHERALS {GPIO#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#GPIO#Enet 0#Enet 0#Enet 0#Enet\
0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#UART 1#UART 1#GPIO#GPIO#Enet 0#Enet\
0} \
    CONFIG.PCW_MIO_TREE_SIGNALS {gpio[0]#qspi0_ss_b#qspi0_io[0]#qspi0_io[1]#qspi0_io[2]#qspi0_io[3]/HOLD_B#qspi0_sclk#gpio[7]#gpio[8]#gpio[9]#gpio[10]#gpio[11]#gpio[12]#gpio[13]#gpio[14]#gpio[15]#tx_clk#txd[0]#txd[1]#txd[2]#txd[3]#tx_ctl#rx_clk#rxd[0]#rxd[1]#rxd[2]#rxd[3]#rx_ctl#data[4]#dir#stp#nxt#data[0]#data[1]#data[2]#data[3]#clk#data[5]#data[6]#data[7]#clk#cmd#data[0]#data[1]#data[2]#data[3]#wp#cd#tx#rx#gpio[50]#gpio[51]#mdc#mdio}\
\
    CONFIG.PCW_NAND_CYCLES_T_AR {1} \
    CONFIG.PCW_NAND_CYCLES_T_CLR {1} \
    CONFIG.PCW_NAND_CYCLES_T_RC {11} \
    CONFIG.PCW_NAND_CYCLES_T_REA {1} \
    CONFIG.PCW_NAND_CYCLES_T_RR {1} \
    CONFIG.PCW_NAND_CYCLES_T_WC {11} \
    CONFIG.PCW_NAND_CYCLES_T_WP {1} \
    CONFIG.PCW_NOR_CS0_T_CEOE {1} \
    CONFIG.PCW_NOR_CS0_T_PC {1} \
    CONFIG.PCW_NOR_CS0_T_RC {11} \
    CONFIG.PCW_NOR_CS0_T_TR {1} \
    CONFIG.PCW_NOR_CS0_T_WC {11} \
    CONFIG.PCW_NOR_CS0_T_WP {1} \
    CONFIG.PCW_NOR_CS0_WE_TIME {0} \
    CONFIG.PCW_NOR_CS1_T_CEOE {1} \
    CONFIG.PCW_NOR_CS1_T_PC {1} \
    CONFIG.PCW_NOR_CS1_T_RC {11} \
    CONFIG.PCW_NOR_CS1_T_TR {1} \
    CONFIG.PCW_NOR_CS1_T_WC {11} \
    CONFIG.PCW_NOR_CS1_T_WP {1} \
    CONFIG.PCW_NOR_CS1_WE_TIME {0} \
    CONFIG.PCW_NOR_SRAM_CS0_T_CEOE {1} \
    CONFIG.PCW_NOR_SRAM_CS0_T_PC {1} \
    CONFIG.PCW_NOR_SRAM_CS0_T_RC {11} \
    CONFIG.PCW_NOR_SRAM_CS0_T_TR {1} \
    CONFIG.PCW_NOR_SRAM_CS0_T_WC {11} \
    CONFIG.PCW_NOR_SRAM_CS0_T_WP {1} \
    CONFIG.PCW_NOR_SRAM_CS0_WE_TIME {0} \
    CONFIG.PCW_NOR_SRAM_CS1_T_CEOE {1} \
    CONFIG.PCW_NOR_SRAM_CS1_T_PC {1} \
    CONFIG.PCW_NOR_SRAM_CS1_T_RC {11} \
    CONFIG.PCW_NOR_SRAM_CS1_T_TR {1} \
    CONFIG.PCW_NOR_SRAM_CS1_T_WC {11} \
    CONFIG.PCW_NOR_SRAM_CS1_T_WP {1} \
    CONFIG.PCW_NOR_SRAM_CS1_WE_TIME {0} \
    CONFIG.PCW_OVERRIDE_BASIC_CLOCK {0} \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY0 {0.063} \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY1 {0.062} \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY2 {0.065} \
    CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY3 {0.083} \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_0 {-0.007} \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_1 {-0.010} \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_2 {-0.006} \
    CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_3 {-0.048} \
    CONFIG.PCW_PCAP_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_PCAP_PERIPHERAL_FREQMHZ {200} \
    CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_PLL_BYPASSMODE_ENABLE {0} \
    CONFIG.PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V} \
    CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 1.8V} \
    CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE {0} \
    CONFIG.PCW_QSPI_GRP_IO1_ENABLE {0} \
    CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE {1} \
    CONFIG.PCW_QSPI_GRP_SINGLE_SS_IO {MIO 1 .. 6} \
    CONFIG.PCW_QSPI_GRP_SS1_ENABLE {0} \
    CONFIG.PCW_QSPI_INTERNAL_HIGHADDRESS {0xFCFFFFFF} \
    CONFIG.PCW_QSPI_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ {200.000000} \
    CONFIG.PCW_QSPI_QSPI_IO {MIO 1 .. 6} \
    CONFIG.PCW_SD0_GRP_CD_ENABLE {1} \
    CONFIG.PCW_SD0_GRP_CD_IO {MIO 47} \
    CONFIG.PCW_SD0_GRP_POW_ENABLE {0} \
    CONFIG.PCW_SD0_GRP_WP_ENABLE {1} \
    CONFIG.PCW_SD0_GRP_WP_IO {MIO 46} \
    CONFIG.PCW_SD0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_SD0_SD0_IO {MIO 40 .. 45} \
    CONFIG.PCW_SD1_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_SDIO_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ {50} \
    CONFIG.PCW_SDIO_PERIPHERAL_VALID {1} \
    CONFIG.PCW_SINGLE_QSPI_DATA_MODE {x4} \
    CONFIG.PCW_SMC_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_SMC_PERIPHERAL_VALID {0} \
    CONFIG.PCW_SPI0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_SPI0_SPI0_IO {EMIO} \
    CONFIG.PCW_SPI1_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_SPI1_SPI1_IO {EMIO} \
    CONFIG.PCW_SPI_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_SPI_PERIPHERAL_FREQMHZ {166.666666} \
    CONFIG.PCW_SPI_PERIPHERAL_VALID {1} \
    CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {64} \
    CONFIG.PCW_S_AXI_HP1_DATA_WIDTH {64} \
    CONFIG.PCW_S_AXI_HP2_DATA_WIDTH {64} \
    CONFIG.PCW_S_AXI_HP3_DATA_WIDTH {64} \
    CONFIG.PCW_TPIU_PERIPHERAL_CLKSRC {External} \
    CONFIG.PCW_TRACE_INTERNAL_WIDTH {2} \
    CONFIG.PCW_TRACE_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_TTC0_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
    CONFIG.PCW_TTC0_CLK0_PERIPHERAL_DIVISOR0 {1} \
    CONFIG.PCW_TTC0_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
    CONFIG.PCW_TTC0_CLK1_PERIPHERAL_DIVISOR0 {1} \
    CONFIG.PCW_TTC0_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
    CONFIG.PCW_TTC0_CLK2_PERIPHERAL_DIVISOR0 {1} \
    CONFIG.PCW_TTC0_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_TTC1_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
    CONFIG.PCW_TTC1_CLK0_PERIPHERAL_DIVISOR0 {1} \
    CONFIG.PCW_TTC1_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
    CONFIG.PCW_TTC1_CLK1_PERIPHERAL_DIVISOR0 {1} \
    CONFIG.PCW_TTC1_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
    CONFIG.PCW_TTC1_CLK2_PERIPHERAL_DIVISOR0 {1} \
    CONFIG.PCW_TTC1_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_UART0_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_UART1_BAUD_RATE {115200} \
    CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} \
    CONFIG.PCW_UART1_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_UART1_UART1_IO {MIO 48 .. 49} \
    CONFIG.PCW_UART_PERIPHERAL_CLKSRC {IO PLL} \
    CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {50} \
    CONFIG.PCW_UART_PERIPHERAL_VALID {1} \
    CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {533.333374} \
    CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE {0} \
    CONFIG.PCW_UIPARAM_DDR_AL {0} \
    CONFIG.PCW_UIPARAM_DDR_BL {8} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.41} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.411} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.341} \
    CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.358} \
    CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {32 Bit} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH {61.0905} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH {61.0905} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH {61.0905} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH {61.0905} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN {0} \
    CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH {68.4725} \
    CONFIG.PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH {71.086} \
    CONFIG.PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH {66.794} \
    CONFIG.PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH {108.7385} \
    CONFIG.PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 {0.025} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 {0.028} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 {-0.009} \
    CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 {-0.061} \
    CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH {64.1705} \
    CONFIG.PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH {63.686} \
    CONFIG.PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH {68.46} \
    CONFIG.PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM {0} \
    CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH {105.4895} \
    CONFIG.PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY {160} \
    CONFIG.PCW_UIPARAM_DDR_ENABLE {1} \
    CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ {533.333313} \
    CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP {Normal (0-85)} \
    CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3} \
    CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41J128M16 HA-15E} \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE {1} \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE {1} \
    CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL {1} \
    CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF {1} \
    CONFIG.PCW_USB0_PERIPHERAL_ENABLE {1} \
    CONFIG.PCW_USB0_RESET_ENABLE {0} \
    CONFIG.PCW_USB0_USB0_IO {MIO 28 .. 39} \
    CONFIG.PCW_USB1_PERIPHERAL_ENABLE {0} \
    CONFIG.PCW_USB_RESET_ENABLE {1} \
    CONFIG.PCW_USB_RESET_POLARITY {Active Low} \
    CONFIG.PCW_USB_RESET_SELECT {Share reset pin} \
    CONFIG.PCW_USE_AXI_NONSECURE {0} \
    CONFIG.PCW_USE_CROSS_TRIGGER {0} \
    CONFIG.PCW_USE_DMA0 {1} \
    CONFIG.PCW_USE_DMA1 {1} \
    CONFIG.PCW_USE_DMA2 {1} \
    CONFIG.PCW_USE_FABRIC_INTERRUPT {1} \
    CONFIG.PCW_USE_S_AXI_HP0 {1} \
    CONFIG.PCW_USE_S_AXI_HP1 {1} \
    CONFIG.PCW_WDT_PERIPHERAL_CLKSRC {CPU_1X} \
    CONFIG.PCW_WDT_PERIPHERAL_DIVISOR0 {1} \
    CONFIG.PCW_WDT_PERIPHERAL_ENABLE {0} \
  ] $sys_ps7


  # Create instance: axi_iic_main, and set properties
  set axi_iic_main [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 axi_iic_main ]
  set_property -dict [list \
    CONFIG.IIC_BOARD_INTERFACE {Custom} \
    CONFIG.USE_BOARD_FLOW {true} \
  ] $axi_iic_main


  # Create instance: sys_i2c_mixer, and set properties
  set sys_i2c_mixer [ create_bd_cell -type ip -vlnv analog.com:user:util_i2c_mixer:1.0 sys_i2c_mixer ]

  # Create instance: sys_concat_intc, and set properties
  set sys_concat_intc [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconcat:1.0 sys_concat_intc ]
  set_property CONFIG.NUM_PORTS {16} $sys_concat_intc


  # Create instance: sys_rstgen, and set properties
  set sys_rstgen [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 sys_rstgen ]
  set_property CONFIG.C_EXT_RST_WIDTH {1} $sys_rstgen


  # Create instance: sys_200m_rstgen, and set properties
  set sys_200m_rstgen [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 sys_200m_rstgen ]
  set_property CONFIG.C_EXT_RST_WIDTH {1} $sys_200m_rstgen


  # Create instance: sys_logic_inv, and set properties
  set sys_logic_inv [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilvector_logic:1.0 sys_logic_inv ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $sys_logic_inv


  # Create instance: axi_hdmi_clkgen, and set properties
  set axi_hdmi_clkgen [ create_bd_cell -type ip -vlnv analog.com:user:axi_clkgen:1.0 axi_hdmi_clkgen ]

  # Create instance: axi_hdmi_core, and set properties
  set axi_hdmi_core [ create_bd_cell -type ip -vlnv analog.com:user:axi_hdmi_tx:1.0 axi_hdmi_core ]
  set_property CONFIG.INTERFACE {16_BIT} $axi_hdmi_core


  # Create instance: axi_hdmi_dma, and set properties
  set axi_hdmi_dma [ create_bd_cell -type ip -vlnv analog.com:user:axi_dmac:1.0 axi_hdmi_dma ]
  set_property -dict [list \
    CONFIG.AXI_SLICE_DEST {false} \
    CONFIG.AXI_SLICE_SRC {false} \
    CONFIG.CYCLIC {true} \
    CONFIG.DMA_2D_TRANSFER {true} \
    CONFIG.DMA_DATA_WIDTH_SRC {64} \
    CONFIG.DMA_TYPE_DEST {1} \
    CONFIG.DMA_TYPE_SRC {0} \
  ] $axi_hdmi_dma


  # Create instance: sys_audio_clkgen, and set properties
  set sys_audio_clkgen [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 sys_audio_clkgen ]
  set_property -dict [list \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {12.288} \
    CONFIG.PRIM_SOURCE {No_buffer} \
    CONFIG.RESET_TYPE {ACTIVE_LOW} \
    CONFIG.USE_LOCKED {false} \
    CONFIG.USE_PHASE_ALIGNMENT {false} \
    CONFIG.USE_RESET {true} \
  ] $sys_audio_clkgen


  # Create instance: axi_spdif_tx_core, and set properties
  set axi_spdif_tx_core [ create_bd_cell -type ip -vlnv analog.com:user:axi_spdif_tx:1.0 axi_spdif_tx_core ]
  set_property -dict [list \
    CONFIG.DMA_TYPE {1} \
    CONFIG.S_AXI_ADDRESS_WIDTH {16} \
  ] $axi_spdif_tx_core


  # Create instance: axi_i2s_adi, and set properties
  set axi_i2s_adi [ create_bd_cell -type ip -vlnv analog.com:user:axi_i2s_adi:1.0 axi_i2s_adi ]
  set_property -dict [list \
    CONFIG.DMA_TYPE {1} \
    CONFIG.S_AXI_ADDRESS_WIDTH {16} \
  ] $axi_i2s_adi


  # Create instance: axi_iic_fmc, and set properties
  set axi_iic_fmc [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_iic:2.1 axi_iic_fmc ]

  # Create instance: axi_sysid_0, and set properties
  set axi_sysid_0 [ create_bd_cell -type ip -vlnv analog.com:user:axi_sysid:1.0 axi_sysid_0 ]
  set_property CONFIG.ROM_ADDR_BITS {9} $axi_sysid_0


  # Create instance: rom_sys_0, and set properties
  set rom_sys_0 [ create_bd_cell -type ip -vlnv analog.com:user:sysid_rom:1.0 rom_sys_0 ]
  set_property -dict [list \
    CONFIG.PATH_TO_FILE {/home/madi1/_GIT/irs-systems/ADI-hdl/projects/ad7606x_fmc/zed/INTF0_ADCNBITS18/mem_init_sys.txt} \
    CONFIG.ROM_ADDR_BITS {9} \
  ] $rom_sys_0


  # Create instance: GND_1, and set properties
  set GND_1 [ create_bd_cell -type inline_hdl -vlnv xilinx.com:inline_hdl:ilconstant:1.0 GND_1 ]
  set_property -dict [list \
    CONFIG.CONST_VAL {0} \
    CONFIG.CONST_WIDTH {1} \
  ] $GND_1


  # Create instance: axi_gp0_interconnect, and set properties
  set axi_gp0_interconnect [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_gp0_interconnect ]
  set_property CONFIG.NUM_MI {11} $axi_gp0_interconnect


  # Create instance: axi_hp0_interconnect, and set properties
  set axi_hp0_interconnect [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_hp0_interconnect ]
  set_property -dict [list \
    CONFIG.NUM_MI {1} \
    CONFIG.NUM_SI {1} \
  ] $axi_hp0_interconnect


  # Create instance: ad7606_pwm_gen, and set properties
  set ad7606_pwm_gen [ create_bd_cell -type ip -vlnv analog.com:user:axi_pwm_gen:1.0 ad7606_pwm_gen ]
  set_property -dict [list \
    CONFIG.ASYNC_CLK_EN {false} \
    CONFIG.N_PWMS {1} \
    CONFIG.PULSE_0_PERIOD {125} \
    CONFIG.PULSE_0_WIDTH {124} \
  ] $ad7606_pwm_gen


  # Create instance: axi_ad7606x_dma, and set properties
  set axi_ad7606x_dma [ create_bd_cell -type ip -vlnv analog.com:user:axi_dmac:1.0 axi_ad7606x_dma ]
  set_property -dict [list \
    CONFIG.CYCLIC {false} \
    CONFIG.DMA_2D_TRANSFER {false} \
    CONFIG.DMA_DATA_WIDTH_DEST {64} \
    CONFIG.DMA_DATA_WIDTH_SRC {256} \
    CONFIG.DMA_TYPE_DEST {0} \
    CONFIG.DMA_TYPE_SRC {2} \
    CONFIG.SYNC_TRANSFER_START {true} \
  ] $axi_ad7606x_dma


  # Create instance: axi_ad7606x, and set properties
  set axi_ad7606x [ create_bd_cell -type ip -vlnv analog.com:user:axi_ad7606x:1.0 axi_ad7606x ]
  set_property -dict [list \
    CONFIG.ADC_N_BITS {18} \
    CONFIG.ADC_TO_DMA_N_BITS {32} \
  ] $axi_ad7606x


  # Create instance: ad7606x_adc_pack, and set properties
  set ad7606x_adc_pack [ create_bd_cell -type ip -vlnv analog.com:user:util_cpack2:1.0 ad7606x_adc_pack ]
  set_property -dict [list \
    CONFIG.NUM_OF_CHANNELS {8} \
    CONFIG.SAMPLE_DATA_WIDTH {32} \
  ] $ad7606x_adc_pack


  # Create instance: axi_hp1_interconnect, and set properties
  set axi_hp1_interconnect [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_hp1_interconnect ]
  set_property -dict [list \
    CONFIG.NUM_MI {1} \
    CONFIG.NUM_SI {1} \
  ] $axi_hp1_interconnect


  # Create interface connections
  connect_bd_intf_net -intf_net S00_AXI_1 [get_bd_intf_pins axi_gp0_interconnect/S00_AXI] [get_bd_intf_pins sys_ps7/M_AXI_GP0]
  connect_bd_intf_net -intf_net S00_AXI_2 [get_bd_intf_pins axi_hp0_interconnect/S00_AXI] [get_bd_intf_pins axi_hdmi_dma/m_src_axi]
  connect_bd_intf_net -intf_net S00_AXI_3 [get_bd_intf_pins axi_hp1_interconnect/S00_AXI] [get_bd_intf_pins axi_ad7606x_dma/m_dest_axi]
  connect_bd_intf_net -intf_net ad7606x_adc_pack_packed_fifo_wr [get_bd_intf_pins ad7606x_adc_pack/packed_fifo_wr] [get_bd_intf_pins axi_ad7606x_dma/fifo_wr]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M00_AXI [get_bd_intf_pins axi_gp0_interconnect/M00_AXI] [get_bd_intf_pins axi_iic_main/S_AXI]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M01_AXI [get_bd_intf_pins axi_gp0_interconnect/M01_AXI] [get_bd_intf_pins axi_sysid_0/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M02_AXI [get_bd_intf_pins axi_gp0_interconnect/M02_AXI] [get_bd_intf_pins axi_hdmi_clkgen/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M03_AXI [get_bd_intf_pins axi_gp0_interconnect/M03_AXI] [get_bd_intf_pins axi_hdmi_dma/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M04_AXI [get_bd_intf_pins axi_gp0_interconnect/M04_AXI] [get_bd_intf_pins axi_hdmi_core/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M05_AXI [get_bd_intf_pins axi_gp0_interconnect/M05_AXI] [get_bd_intf_pins axi_spdif_tx_core/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M06_AXI [get_bd_intf_pins axi_gp0_interconnect/M06_AXI] [get_bd_intf_pins axi_i2s_adi/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M07_AXI [get_bd_intf_pins axi_gp0_interconnect/M07_AXI] [get_bd_intf_pins axi_iic_fmc/S_AXI]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M08_AXI [get_bd_intf_pins axi_gp0_interconnect/M08_AXI] [get_bd_intf_pins axi_ad7606x/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M09_AXI [get_bd_intf_pins axi_gp0_interconnect/M09_AXI] [get_bd_intf_pins axi_ad7606x_dma/s_axi]
  connect_bd_intf_net -intf_net axi_gp0_interconnect_M10_AXI [get_bd_intf_pins axi_gp0_interconnect/M10_AXI] [get_bd_intf_pins ad7606_pwm_gen/s_axi]
  connect_bd_intf_net -intf_net axi_hdmi_dma_m_axis [get_bd_intf_pins axi_hdmi_dma/m_axis] [get_bd_intf_pins axi_hdmi_core/s_axis]
  connect_bd_intf_net -intf_net axi_hp0_interconnect_M00_AXI [get_bd_intf_pins axi_hp0_interconnect/M00_AXI] [get_bd_intf_pins sys_ps7/S_AXI_HP0]
  connect_bd_intf_net -intf_net axi_hp1_interconnect_M00_AXI [get_bd_intf_pins axi_hp1_interconnect/M00_AXI] [get_bd_intf_pins sys_ps7/S_AXI_HP1]
  connect_bd_intf_net -intf_net axi_i2s_adi_dma_req_rx [get_bd_intf_pins sys_ps7/DMA2_REQ] [get_bd_intf_pins axi_i2s_adi/dma_req_rx]
  connect_bd_intf_net -intf_net axi_i2s_adi_dma_req_tx [get_bd_intf_pins sys_ps7/DMA1_REQ] [get_bd_intf_pins axi_i2s_adi/dma_req_tx]
  connect_bd_intf_net -intf_net axi_i2s_adi_i2s [get_bd_intf_ports i2s] [get_bd_intf_pins axi_i2s_adi/i2s]
  connect_bd_intf_net -intf_net axi_iic_fmc_IIC [get_bd_intf_ports iic_fmc] [get_bd_intf_pins axi_iic_fmc/IIC]
  connect_bd_intf_net -intf_net axi_iic_main_IIC [get_bd_intf_pins axi_iic_main/IIC] [get_bd_intf_pins sys_i2c_mixer/upstream]
  connect_bd_intf_net -intf_net axi_spdif_tx_core_dma_req [get_bd_intf_pins sys_ps7/DMA0_REQ] [get_bd_intf_pins axi_spdif_tx_core/dma_req]
  connect_bd_intf_net -intf_net sys_ps7_DDR [get_bd_intf_ports ddr] [get_bd_intf_pins sys_ps7/DDR]
  connect_bd_intf_net -intf_net sys_ps7_DMA0_ACK [get_bd_intf_pins sys_ps7/DMA0_ACK] [get_bd_intf_pins axi_spdif_tx_core/dma_ack]
  connect_bd_intf_net -intf_net sys_ps7_DMA1_ACK [get_bd_intf_pins sys_ps7/DMA1_ACK] [get_bd_intf_pins axi_i2s_adi/dma_ack_tx]
  connect_bd_intf_net -intf_net sys_ps7_DMA2_ACK [get_bd_intf_pins sys_ps7/DMA2_ACK] [get_bd_intf_pins axi_i2s_adi/dma_ack_rx]
  connect_bd_intf_net -intf_net sys_ps7_FIXED_IO [get_bd_intf_ports fixed_io] [get_bd_intf_pins sys_ps7/FIXED_IO]

  # Create port connections
  connect_bd_net -net GND_1_dout  [get_bd_pins GND_1/dout] \
  [get_bd_pins sys_concat_intc/In12] \
  [get_bd_pins sys_concat_intc/In10] \
  [get_bd_pins sys_concat_intc/In9] \
  [get_bd_pins sys_concat_intc/In8] \
  [get_bd_pins sys_concat_intc/In7] \
  [get_bd_pins sys_concat_intc/In6] \
  [get_bd_pins sys_concat_intc/In5] \
  [get_bd_pins sys_concat_intc/In4] \
  [get_bd_pins sys_concat_intc/In3] \
  [get_bd_pins sys_concat_intc/In2] \
  [get_bd_pins sys_concat_intc/In1] \
  [get_bd_pins sys_concat_intc/In0]
  connect_bd_net -net ad7606_pwm_gen_pwm_0  [get_bd_pins ad7606_pwm_gen/pwm_0] \
  [get_bd_ports rx_cnvst_n]
  connect_bd_net -net ad7606x_adc_pack_fifo_wr_overflow  [get_bd_pins ad7606x_adc_pack/fifo_wr_overflow] \
  [get_bd_pins axi_ad7606x/adc_dovf]
  connect_bd_net -net ad7606x_adc_pack_packed_sync  [get_bd_pins ad7606x_adc_pack/packed_sync] \
  [get_bd_pins axi_ad7606x_dma/sync]
  connect_bd_net -net axi_ad7606x_adc_clk  [get_bd_pins axi_ad7606x/adc_clk] \
  [get_bd_pins ad7606x_adc_pack/clk] \
  [get_bd_pins axi_ad7606x_dma/fifo_wr_clk]
  connect_bd_net -net axi_ad7606x_adc_data_0  [get_bd_pins axi_ad7606x/adc_data_0] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_0]
  connect_bd_net -net axi_ad7606x_adc_data_1  [get_bd_pins axi_ad7606x/adc_data_1] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_1]
  connect_bd_net -net axi_ad7606x_adc_data_2  [get_bd_pins axi_ad7606x/adc_data_2] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_2]
  connect_bd_net -net axi_ad7606x_adc_data_3  [get_bd_pins axi_ad7606x/adc_data_3] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_3]
  connect_bd_net -net axi_ad7606x_adc_data_4  [get_bd_pins axi_ad7606x/adc_data_4] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_4]
  connect_bd_net -net axi_ad7606x_adc_data_5  [get_bd_pins axi_ad7606x/adc_data_5] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_5]
  connect_bd_net -net axi_ad7606x_adc_data_6  [get_bd_pins axi_ad7606x/adc_data_6] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_6]
  connect_bd_net -net axi_ad7606x_adc_data_7  [get_bd_pins axi_ad7606x/adc_data_7] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_data_7]
  connect_bd_net -net axi_ad7606x_adc_enable_0  [get_bd_pins axi_ad7606x/adc_enable_0] \
  [get_bd_pins ad7606x_adc_pack/enable_0]
  connect_bd_net -net axi_ad7606x_adc_enable_1  [get_bd_pins axi_ad7606x/adc_enable_1] \
  [get_bd_pins ad7606x_adc_pack/enable_1]
  connect_bd_net -net axi_ad7606x_adc_enable_2  [get_bd_pins axi_ad7606x/adc_enable_2] \
  [get_bd_pins ad7606x_adc_pack/enable_2]
  connect_bd_net -net axi_ad7606x_adc_enable_3  [get_bd_pins axi_ad7606x/adc_enable_3] \
  [get_bd_pins ad7606x_adc_pack/enable_3]
  connect_bd_net -net axi_ad7606x_adc_enable_4  [get_bd_pins axi_ad7606x/adc_enable_4] \
  [get_bd_pins ad7606x_adc_pack/enable_4]
  connect_bd_net -net axi_ad7606x_adc_enable_5  [get_bd_pins axi_ad7606x/adc_enable_5] \
  [get_bd_pins ad7606x_adc_pack/enable_5]
  connect_bd_net -net axi_ad7606x_adc_enable_6  [get_bd_pins axi_ad7606x/adc_enable_6] \
  [get_bd_pins ad7606x_adc_pack/enable_6]
  connect_bd_net -net axi_ad7606x_adc_enable_7  [get_bd_pins axi_ad7606x/adc_enable_7] \
  [get_bd_pins ad7606x_adc_pack/enable_7]
  connect_bd_net -net axi_ad7606x_adc_reset  [get_bd_pins axi_ad7606x/adc_reset] \
  [get_bd_pins ad7606x_adc_pack/reset]
  connect_bd_net -net axi_ad7606x_adc_valid  [get_bd_pins axi_ad7606x/adc_valid] \
  [get_bd_pins ad7606x_adc_pack/fifo_wr_en]
  connect_bd_net -net axi_ad7606x_dma_irq  [get_bd_pins axi_ad7606x_dma/irq] \
  [get_bd_pins sys_concat_intc/In13]
  connect_bd_net -net axi_ad7606x_rx_cs_n  [get_bd_pins axi_ad7606x/rx_cs_n] \
  [get_bd_ports rx_cs_n]
  connect_bd_net -net axi_ad7606x_rx_db_o  [get_bd_pins axi_ad7606x/rx_db_o] \
  [get_bd_ports rx_db_o]
  connect_bd_net -net axi_ad7606x_rx_db_t  [get_bd_pins axi_ad7606x/rx_db_t] \
  [get_bd_ports rx_db_t]
  connect_bd_net -net axi_ad7606x_rx_rd_n  [get_bd_pins axi_ad7606x/rx_rd_n] \
  [get_bd_ports rx_rd_n]
  connect_bd_net -net axi_ad7606x_rx_wr_n  [get_bd_pins axi_ad7606x/rx_wr_n] \
  [get_bd_ports rx_wr_n]
  connect_bd_net -net axi_hdmi_clkgen_clk_0  [get_bd_pins axi_hdmi_clkgen/clk_0] \
  [get_bd_pins axi_hdmi_core/reference_clk]
  connect_bd_net -net axi_hdmi_core_hdmi_16_data  [get_bd_pins axi_hdmi_core/hdmi_16_data] \
  [get_bd_ports hdmi_data]
  connect_bd_net -net axi_hdmi_core_hdmi_16_data_e  [get_bd_pins axi_hdmi_core/hdmi_16_data_e] \
  [get_bd_ports hdmi_data_e]
  connect_bd_net -net axi_hdmi_core_hdmi_16_hsync  [get_bd_pins axi_hdmi_core/hdmi_16_hsync] \
  [get_bd_ports hdmi_hsync]
  connect_bd_net -net axi_hdmi_core_hdmi_16_vsync  [get_bd_pins axi_hdmi_core/hdmi_16_vsync] \
  [get_bd_ports hdmi_vsync]
  connect_bd_net -net axi_hdmi_core_hdmi_out_clk  [get_bd_pins axi_hdmi_core/hdmi_out_clk] \
  [get_bd_ports hdmi_out_clk]
  connect_bd_net -net axi_hdmi_dma_irq  [get_bd_pins axi_hdmi_dma/irq] \
  [get_bd_pins sys_concat_intc/In15]
  connect_bd_net -net axi_iic_fmc_iic2intc_irpt  [get_bd_pins axi_iic_fmc/iic2intc_irpt] \
  [get_bd_pins sys_concat_intc/In11]
  connect_bd_net -net axi_iic_main_iic2intc_irpt  [get_bd_pins axi_iic_main/iic2intc_irpt] \
  [get_bd_pins sys_concat_intc/In14]
  connect_bd_net -net axi_spdif_tx_core_spdif_tx_o  [get_bd_pins axi_spdif_tx_core/spdif_tx_o] \
  [get_bd_ports spdif]
  connect_bd_net -net axi_sysid_0_rom_addr  [get_bd_pins axi_sysid_0/rom_addr] \
  [get_bd_pins rom_sys_0/rom_addr]
  connect_bd_net -net gpio_i_1  [get_bd_ports gpio_i] \
  [get_bd_pins sys_ps7/GPIO_I]
  connect_bd_net -net iic_mux_scl_i_1  [get_bd_ports iic_mux_scl_i] \
  [get_bd_pins sys_i2c_mixer/downstream_scl_I]
  connect_bd_net -net iic_mux_sda_i_1  [get_bd_ports iic_mux_sda_i] \
  [get_bd_pins sys_i2c_mixer/downstream_sda_I]
  connect_bd_net -net otg_vbusoc_1  [get_bd_ports otg_vbusoc] \
  [get_bd_pins sys_logic_inv/Op1]
  connect_bd_net -net rom_sys_0_rom_data  [get_bd_pins rom_sys_0/rom_data] \
  [get_bd_pins axi_sysid_0/sys_rom_data]
  connect_bd_net -net rx_busy_1  [get_bd_ports rx_busy] \
  [get_bd_pins axi_ad7606x/rx_busy]
  connect_bd_net -net rx_db_i_1  [get_bd_ports rx_db_i] \
  [get_bd_pins axi_ad7606x/rx_db_i]
  connect_bd_net -net rx_first_data_1  [get_bd_ports rx_first_data] \
  [get_bd_pins axi_ad7606x/first_data]
  connect_bd_net -net spi0_clk_i_1  [get_bd_ports spi0_clk_i] \
  [get_bd_pins sys_ps7/SPI0_SCLK_I]
  connect_bd_net -net spi0_csn_i_1  [get_bd_ports spi0_csn_i] \
  [get_bd_pins sys_ps7/SPI0_SS_I]
  connect_bd_net -net spi0_sdi_i_1  [get_bd_ports spi0_sdi_i] \
  [get_bd_pins sys_ps7/SPI0_MISO_I]
  connect_bd_net -net spi0_sdo_i_1  [get_bd_ports spi0_sdo_i] \
  [get_bd_pins sys_ps7/SPI0_MOSI_I]
  connect_bd_net -net spi1_clk_i_1  [get_bd_ports spi1_clk_i] \
  [get_bd_pins sys_ps7/SPI1_SCLK_I]
  connect_bd_net -net spi1_csn_i_1  [get_bd_ports spi1_csn_i] \
  [get_bd_pins sys_ps7/SPI1_SS_I]
  connect_bd_net -net spi1_sdi_i_1  [get_bd_ports spi1_sdi_i] \
  [get_bd_pins sys_ps7/SPI1_MISO_I]
  connect_bd_net -net spi1_sdo_i_1  [get_bd_ports spi1_sdo_i] \
  [get_bd_pins sys_ps7/SPI1_MOSI_I]
  connect_bd_net -net sys_200m_clk  [get_bd_pins sys_ps7/FCLK_CLK1] \
  [get_bd_pins sys_200m_rstgen/slowest_sync_clk] \
  [get_bd_pins axi_hdmi_clkgen/clk] \
  [get_bd_pins sys_audio_clkgen/clk_in1]
  connect_bd_net -net sys_200m_reset  [get_bd_pins sys_200m_rstgen/peripheral_reset]
  connect_bd_net -net sys_200m_resetn  [get_bd_pins sys_200m_rstgen/peripheral_aresetn]
  connect_bd_net -net sys_audio_clkgen_clk_out1  [get_bd_pins sys_audio_clkgen/clk_out1] \
  [get_bd_pins axi_spdif_tx_core/spdif_data_clk] \
  [get_bd_ports i2s_mclk] \
  [get_bd_pins axi_i2s_adi/data_clk_i]
  connect_bd_net -net sys_concat_intc_dout  [get_bd_pins sys_concat_intc/dout] \
  [get_bd_pins sys_ps7/IRQ_F2P]
  connect_bd_net -net sys_cpu_clk  [get_bd_pins sys_ps7/FCLK_CLK0] \
  [get_bd_pins sys_rstgen/slowest_sync_clk] \
  [get_bd_pins axi_hdmi_core/vdma_clk] \
  [get_bd_pins axi_hdmi_dma/s_axi_aclk] \
  [get_bd_pins axi_hdmi_dma/m_src_axi_aclk] \
  [get_bd_pins axi_hdmi_dma/m_axis_aclk] \
  [get_bd_pins axi_spdif_tx_core/dma_req_aclk] \
  [get_bd_pins sys_ps7/DMA0_ACLK] \
  [get_bd_pins axi_i2s_adi/dma_req_rx_aclk] \
  [get_bd_pins axi_i2s_adi/dma_req_tx_aclk] \
  [get_bd_pins sys_ps7/DMA1_ACLK] \
  [get_bd_pins sys_ps7/DMA2_ACLK] \
  [get_bd_pins rom_sys_0/clk] \
  [get_bd_pins axi_gp0_interconnect/ACLK] \
  [get_bd_pins axi_gp0_interconnect/S00_ACLK] \
  [get_bd_pins sys_ps7/M_AXI_GP0_ACLK] \
  [get_bd_pins axi_gp0_interconnect/M00_ACLK] \
  [get_bd_pins axi_iic_main/s_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M01_ACLK] \
  [get_bd_pins axi_sysid_0/s_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M02_ACLK] \
  [get_bd_pins axi_hdmi_clkgen/s_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M03_ACLK] \
  [get_bd_pins axi_gp0_interconnect/M04_ACLK] \
  [get_bd_pins axi_hdmi_core/s_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M05_ACLK] \
  [get_bd_pins axi_spdif_tx_core/s_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M06_ACLK] \
  [get_bd_pins axi_i2s_adi/s_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M07_ACLK] \
  [get_bd_pins axi_iic_fmc/s_axi_aclk] \
  [get_bd_pins axi_hp0_interconnect/ACLK] \
  [get_bd_pins axi_hp0_interconnect/M00_ACLK] \
  [get_bd_pins sys_ps7/S_AXI_HP0_ACLK] \
  [get_bd_pins axi_hp0_interconnect/S00_ACLK] \
  [get_bd_pins axi_ad7606x_dma/s_axi_aclk] \
  [get_bd_pins ad7606_pwm_gen/s_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M08_ACLK] \
  [get_bd_pins axi_ad7606x/s_axi_aclk] \
  [get_bd_pins axi_hp1_interconnect/ACLK] \
  [get_bd_pins axi_hp1_interconnect/M00_ACLK] \
  [get_bd_pins sys_ps7/S_AXI_HP1_ACLK] \
  [get_bd_pins axi_hp1_interconnect/S00_ACLK] \
  [get_bd_pins axi_ad7606x_dma/m_dest_axi_aclk] \
  [get_bd_pins axi_gp0_interconnect/M09_ACLK] \
  [get_bd_pins axi_gp0_interconnect/M10_ACLK]
  connect_bd_net -net sys_cpu_reset  [get_bd_pins sys_rstgen/peripheral_reset]
  connect_bd_net -net sys_cpu_resetn  [get_bd_pins sys_rstgen/peripheral_aresetn] \
  [get_bd_pins axi_hdmi_dma/s_axi_aresetn] \
  [get_bd_pins axi_hdmi_dma/m_src_axi_aresetn] \
  [get_bd_pins axi_spdif_tx_core/dma_req_rstn] \
  [get_bd_pins sys_audio_clkgen/resetn] \
  [get_bd_pins axi_i2s_adi/dma_req_tx_rstn] \
  [get_bd_pins axi_i2s_adi/dma_req_rx_rstn] \
  [get_bd_pins axi_gp0_interconnect/ARESETN] \
  [get_bd_pins axi_gp0_interconnect/S00_ARESETN] \
  [get_bd_pins axi_gp0_interconnect/M00_ARESETN] \
  [get_bd_pins axi_iic_main/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M01_ARESETN] \
  [get_bd_pins axi_sysid_0/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M02_ARESETN] \
  [get_bd_pins axi_hdmi_clkgen/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M03_ARESETN] \
  [get_bd_pins axi_gp0_interconnect/M04_ARESETN] \
  [get_bd_pins axi_hdmi_core/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M05_ARESETN] \
  [get_bd_pins axi_spdif_tx_core/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M06_ARESETN] \
  [get_bd_pins axi_i2s_adi/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M07_ARESETN] \
  [get_bd_pins axi_iic_fmc/s_axi_aresetn] \
  [get_bd_pins axi_hp0_interconnect/ARESETN] \
  [get_bd_pins axi_hp0_interconnect/M00_ARESETN] \
  [get_bd_pins axi_hp0_interconnect/S00_ARESETN] \
  [get_bd_pins ad7606_pwm_gen/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M08_ARESETN] \
  [get_bd_pins axi_ad7606x/s_axi_aresetn] \
  [get_bd_pins axi_hp1_interconnect/ARESETN] \
  [get_bd_pins axi_hp1_interconnect/M00_ARESETN] \
  [get_bd_pins axi_hp1_interconnect/S00_ARESETN] \
  [get_bd_pins axi_ad7606x_dma/m_dest_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M09_ARESETN] \
  [get_bd_pins axi_ad7606x_dma/s_axi_aresetn] \
  [get_bd_pins axi_gp0_interconnect/M10_ARESETN]
  connect_bd_net -net sys_i2c_mixer_downstream_scl_O  [get_bd_pins sys_i2c_mixer/downstream_scl_O] \
  [get_bd_ports iic_mux_scl_o]
  connect_bd_net -net sys_i2c_mixer_downstream_scl_T  [get_bd_pins sys_i2c_mixer/downstream_scl_T] \
  [get_bd_ports iic_mux_scl_t]
  connect_bd_net -net sys_i2c_mixer_downstream_sda_O  [get_bd_pins sys_i2c_mixer/downstream_sda_O] \
  [get_bd_ports iic_mux_sda_o]
  connect_bd_net -net sys_i2c_mixer_downstream_sda_T  [get_bd_pins sys_i2c_mixer/downstream_sda_T] \
  [get_bd_ports iic_mux_sda_t]
  connect_bd_net -net sys_logic_inv_Res  [get_bd_pins sys_logic_inv/Res] \
  [get_bd_pins sys_ps7/USB0_VBUS_PWRFAULT]
  connect_bd_net -net sys_ps7_FCLK_RESET0_N  [get_bd_pins sys_ps7/FCLK_RESET0_N] \
  [get_bd_pins sys_rstgen/ext_reset_in]
  connect_bd_net -net sys_ps7_FCLK_RESET1_N  [get_bd_pins sys_ps7/FCLK_RESET1_N] \
  [get_bd_pins sys_200m_rstgen/ext_reset_in]
  connect_bd_net -net sys_ps7_GPIO_O  [get_bd_pins sys_ps7/GPIO_O] \
  [get_bd_ports gpio_o]
  connect_bd_net -net sys_ps7_GPIO_T  [get_bd_pins sys_ps7/GPIO_T] \
  [get_bd_ports gpio_t]
  connect_bd_net -net sys_ps7_SPI0_MOSI_O  [get_bd_pins sys_ps7/SPI0_MOSI_O] \
  [get_bd_ports spi0_sdo_o]
  connect_bd_net -net sys_ps7_SPI0_SCLK_O  [get_bd_pins sys_ps7/SPI0_SCLK_O] \
  [get_bd_ports spi0_clk_o]
  connect_bd_net -net sys_ps7_SPI0_SS1_O  [get_bd_pins sys_ps7/SPI0_SS1_O] \
  [get_bd_ports spi0_csn_1_o]
  connect_bd_net -net sys_ps7_SPI0_SS2_O  [get_bd_pins sys_ps7/SPI0_SS2_O] \
  [get_bd_ports spi0_csn_2_o]
  connect_bd_net -net sys_ps7_SPI0_SS_O  [get_bd_pins sys_ps7/SPI0_SS_O] \
  [get_bd_ports spi0_csn_0_o]
  connect_bd_net -net sys_ps7_SPI1_MOSI_O  [get_bd_pins sys_ps7/SPI1_MOSI_O] \
  [get_bd_ports spi1_sdo_o]
  connect_bd_net -net sys_ps7_SPI1_SCLK_O  [get_bd_pins sys_ps7/SPI1_SCLK_O] \
  [get_bd_ports spi1_clk_o]
  connect_bd_net -net sys_ps7_SPI1_SS1_O  [get_bd_pins sys_ps7/SPI1_SS1_O] \
  [get_bd_ports spi1_csn_1_o]
  connect_bd_net -net sys_ps7_SPI1_SS2_O  [get_bd_pins sys_ps7/SPI1_SS2_O] \
  [get_bd_ports spi1_csn_2_o]
  connect_bd_net -net sys_ps7_SPI1_SS_O  [get_bd_pins sys_ps7/SPI1_SS_O] \
  [get_bd_ports spi1_csn_0_o]

  # Create address segments
  assign_bd_address -offset 0x44B00000 -range 0x00010000 -with_name SEG_data_ad7606_pwm_gen -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs ad7606_pwm_gen/s_axi/axi_lite] -force
  assign_bd_address -offset 0x44A00000 -range 0x00010000 -with_name SEG_data_axi_ad7606x -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_ad7606x/s_axi/axi_lite] -force
  assign_bd_address -offset 0x44A30000 -range 0x00001000 -with_name SEG_data_axi_ad7606x_dma -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_ad7606x_dma/s_axi/axi_lite] -force
  assign_bd_address -offset 0x79000000 -range 0x00010000 -with_name SEG_data_axi_hdmi_clkgen -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_hdmi_clkgen/s_axi/axi_lite] -force
  assign_bd_address -offset 0x70E00000 -range 0x00010000 -with_name SEG_data_axi_hdmi_core -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_hdmi_core/s_axi/axi_lite] -force
  assign_bd_address -offset 0x43000000 -range 0x00001000 -with_name SEG_data_axi_hdmi_dma -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_hdmi_dma/s_axi/axi_lite] -force
  assign_bd_address -offset 0x77600000 -range 0x00010000 -with_name SEG_data_axi_i2s_adi -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_i2s_adi/s_axi/axi_lite] -force
  assign_bd_address -offset 0x41620000 -range 0x00001000 -with_name SEG_data_axi_iic_fmc -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_iic_fmc/S_AXI/Reg] -force
  assign_bd_address -offset 0x41600000 -range 0x00001000 -with_name SEG_data_axi_iic_main -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_iic_main/S_AXI/Reg] -force
  assign_bd_address -offset 0x75C00000 -range 0x00010000 -with_name SEG_data_axi_spdif_tx_core -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_spdif_tx_core/s_axi/axi_lite] -force
  assign_bd_address -offset 0x45000000 -range 0x00010000 -with_name SEG_data_axi_sysid_0 -target_address_space [get_bd_addr_spaces sys_ps7/Data] [get_bd_addr_segs axi_sysid_0/s_axi/axi_lite] -force
  assign_bd_address -offset 0x00000000 -range 0x20000000 -target_address_space [get_bd_addr_spaces axi_hdmi_dma/m_src_axi] [get_bd_addr_segs sys_ps7/S_AXI_HP0/HP0_DDR_LOWOCM] -force
  assign_bd_address -offset 0x00000000 -range 0x20000000 -target_address_space [get_bd_addr_spaces axi_ad7606x_dma/m_dest_axi] [get_bd_addr_segs sys_ps7/S_AXI_HP1/HP1_DDR_LOWOCM] -force

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"1.07111",
   "Default View_TopLeft":"-741,686",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0 TLS
#  -string -flagsOSRD
preplace port ddr -pg 1 -lvl 7 -x 2950 -y 2700 -defaultsOSRD
preplace port fixed_io -pg 1 -lvl 7 -x 2950 -y 2720 -defaultsOSRD
preplace port iic_fmc -pg 1 -lvl 7 -x 2950 -y 3710 -defaultsOSRD
preplace port i2s -pg 1 -lvl 7 -x 2950 -y 2380 -defaultsOSRD
preplace port port-id_spi0_csn_2_o -pg 1 -lvl 7 -x 2950 -y 2920 -defaultsOSRD
preplace port port-id_spi0_csn_1_o -pg 1 -lvl 7 -x 2950 -y 2900 -defaultsOSRD
preplace port port-id_spi0_csn_0_o -pg 1 -lvl 7 -x 2950 -y 2880 -defaultsOSRD
preplace port port-id_spi0_csn_i -pg 1 -lvl 0 -x 0 -y 3390 -defaultsOSRD
preplace port port-id_spi0_clk_i -pg 1 -lvl 0 -x 0 -y 2540 -defaultsOSRD
preplace port port-id_spi0_clk_o -pg 1 -lvl 7 -x 2950 -y 2780 -defaultsOSRD
preplace port port-id_spi0_sdo_i -pg 1 -lvl 0 -x 0 -y 3560 -defaultsOSRD
preplace port port-id_spi0_sdo_o -pg 1 -lvl 7 -x 2950 -y 2820 -defaultsOSRD
preplace port port-id_spi0_sdi_i -pg 1 -lvl 0 -x 0 -y 3510 -defaultsOSRD
preplace port port-id_spi1_csn_2_o -pg 1 -lvl 7 -x 2950 -y 3120 -defaultsOSRD
preplace port port-id_spi1_csn_1_o -pg 1 -lvl 7 -x 2950 -y 3100 -defaultsOSRD
preplace port port-id_spi1_csn_0_o -pg 1 -lvl 7 -x 2950 -y 3080 -defaultsOSRD
preplace port port-id_spi1_csn_i -pg 1 -lvl 0 -x 0 -y 3600 -defaultsOSRD
preplace port port-id_spi1_clk_i -pg 1 -lvl 0 -x 0 -y 3580 -defaultsOSRD
preplace port port-id_spi1_clk_o -pg 1 -lvl 7 -x 2950 -y 2980 -defaultsOSRD
preplace port port-id_spi1_sdo_i -pg 1 -lvl 0 -x 0 -y 3640 -defaultsOSRD
preplace port port-id_spi1_sdo_o -pg 1 -lvl 7 -x 2950 -y 3020 -defaultsOSRD
preplace port port-id_spi1_sdi_i -pg 1 -lvl 0 -x 0 -y 3620 -defaultsOSRD
preplace port port-id_hdmi_out_clk -pg 1 -lvl 7 -x 2950 -y 1950 -defaultsOSRD
preplace port port-id_hdmi_hsync -pg 1 -lvl 7 -x 2950 -y 1970 -defaultsOSRD
preplace port port-id_hdmi_vsync -pg 1 -lvl 7 -x 2950 -y 1990 -defaultsOSRD
preplace port port-id_hdmi_data_e -pg 1 -lvl 7 -x 2950 -y 2010 -defaultsOSRD
preplace port port-id_i2s_mclk -pg 1 -lvl 7 -x 2950 -y 3570 -defaultsOSRD
preplace port port-id_iic_mux_scl_t -pg 1 -lvl 7 -x 2950 -y 1350 -defaultsOSRD
preplace port port-id_iic_mux_sda_t -pg 1 -lvl 7 -x 2950 -y 1390 -defaultsOSRD
preplace port port-id_otg_vbusoc -pg 1 -lvl 0 -x 0 -y 3450 -defaultsOSRD
preplace port port-id_spdif -pg 1 -lvl 7 -x 2950 -y 2100 -defaultsOSRD
preplace port port-id_rx_busy -pg 1 -lvl 0 -x 0 -y 930 -defaultsOSRD
preplace port port-id_rx_cnvst_n -pg 1 -lvl 7 -x 2950 -y 3500 -defaultsOSRD
preplace port port-id_rx_db_t -pg 1 -lvl 7 -x 2950 -y 760 -defaultsOSRD
preplace port port-id_rx_rd_n -pg 1 -lvl 7 -x 2950 -y 780 -defaultsOSRD
preplace port port-id_rx_wr_n -pg 1 -lvl 7 -x 2950 -y 800 -defaultsOSRD
preplace port port-id_rx_cs_n -pg 1 -lvl 7 -x 2950 -y 720 -defaultsOSRD
preplace port port-id_rx_first_data -pg 1 -lvl 0 -x 0 -y 950 -defaultsOSRD
preplace portBus gpio_i -pg 1 -lvl 0 -x 0 -y 2520 -defaultsOSRD
preplace portBus gpio_o -pg 1 -lvl 7 -x 2950 -y 2660 -defaultsOSRD
preplace portBus gpio_t -pg 1 -lvl 7 -x 2950 -y 2680 -defaultsOSRD
preplace portBus hdmi_data -pg 1 -lvl 7 -x 2950 -y 2030 -defaultsOSRD
preplace portBus iic_mux_scl_i -pg 1 -lvl 0 -x 0 -y 1860 -defaultsOSRD
preplace portBus iic_mux_scl_o -pg 1 -lvl 7 -x 2950 -y 1370 -defaultsOSRD
preplace portBus iic_mux_sda_i -pg 1 -lvl 0 -x 0 -y 1880 -defaultsOSRD
preplace portBus iic_mux_sda_o -pg 1 -lvl 7 -x 2950 -y 1410 -defaultsOSRD
preplace portBus rx_db_o -pg 1 -lvl 7 -x 2950 -y 740 -defaultsOSRD
preplace portBus rx_db_i -pg 1 -lvl 0 -x 0 -y 910 -defaultsOSRD
preplace inst sys_ps7 -pg 1 -lvl 5 -x 2210 -y 2970 -defaultsOSRD
preplace inst axi_iic_main -pg 1 -lvl 4 -x 1710 -y 1380 -defaultsOSRD
preplace inst sys_i2c_mixer -pg 1 -lvl 5 -x 2210 -y 1380 -defaultsOSRD
preplace inst sys_concat_intc -pg 1 -lvl 4 -x 1710 -y 1080 -defaultsOSRD
preplace inst sys_rstgen -pg 1 -lvl 1 -x 200 -y 3290 -defaultsOSRD
preplace inst sys_200m_rstgen -pg 1 -lvl 6 -x 2760 -y 3340 -defaultsOSRD
preplace inst sys_logic_inv -pg 1 -lvl 2 -x 710 -y 3450 -defaultsOSRD
preplace inst axi_hdmi_clkgen -pg 1 -lvl 3 -x 1130 -y 2110 -defaultsOSRD
preplace inst axi_hdmi_core -pg 1 -lvl 5 -x 2210 -y 1990 -defaultsOSRD
preplace inst axi_hdmi_dma -pg 1 -lvl 3 -x 1130 -y 1690 -defaultsOSRD
preplace inst sys_audio_clkgen -pg 1 -lvl 6 -x 2760 -y 3640 -defaultsOSRD
preplace inst axi_spdif_tx_core -pg 1 -lvl 4 -x 1710 -y 2090 -defaultsOSRD
preplace inst axi_i2s_adi -pg 1 -lvl 4 -x 1710 -y 2360 -defaultsOSRD
preplace inst axi_iic_fmc -pg 1 -lvl 5 -x 2210 -y 3730 -defaultsOSRD
preplace inst axi_sysid_0 -pg 1 -lvl 3 -x 1130 -y 3270 -defaultsOSRD
preplace inst rom_sys_0 -pg 1 -lvl 2 -x 710 -y 3260 -defaultsOSRD
preplace inst GND_1 -pg 1 -lvl 3 -x 1130 -y 1280 -defaultsOSRD
preplace inst axi_gp0_interconnect -pg 1 -lvl 2 -x 710 -y 2200 -defaultsOSRD
preplace inst axi_hp0_interconnect -pg 1 -lvl 4 -x 1710 -y 1560 -defaultsOSRD
preplace inst ad7606_pwm_gen -pg 1 -lvl 5 -x 2210 -y 3500 -defaultsOSRD
preplace inst axi_ad7606x_dma -pg 1 -lvl 3 -x 1130 -y 1450 -defaultsOSRD
preplace inst axi_ad7606x -pg 1 -lvl 3 -x 1130 -y 950 -defaultsOSRD
preplace inst ad7606x_adc_pack -pg 1 -lvl 2 -x 710 -y 230 -defaultsOSRD
preplace inst axi_hp1_interconnect -pg 1 -lvl 4 -x 1710 -y 1800 -defaultsOSRD
preplace netloc GND_1_dout 1 3 1 1470 930n
preplace netloc ad7606_pwm_gen_pwm_0 1 5 2 NJ 3500 NJ
preplace netloc ad7606x_adc_pack_fifo_wr_overflow 1 2 1 970 230n
preplace netloc ad7606x_adc_pack_packed_sync 1 2 1 960 250n
preplace netloc axi_ad7606x_adc_clk 1 1 3 480 540 940 630 1370
preplace netloc axi_ad7606x_adc_data_0 1 1 3 470 550 NJ 550 1300
preplace netloc axi_ad7606x_adc_data_1 1 1 3 460 560 NJ 560 1310
preplace netloc axi_ad7606x_adc_data_2 1 1 3 450 570 NJ 570 1320
preplace netloc axi_ad7606x_adc_data_3 1 1 3 440 580 NJ 580 1330
preplace netloc axi_ad7606x_adc_data_4 1 1 3 430 590 NJ 590 1340
preplace netloc axi_ad7606x_adc_data_5 1 1 3 420 600 NJ 600 1350
preplace netloc axi_ad7606x_adc_data_6 1 1 3 410 610 NJ 610 1360
preplace netloc axi_ad7606x_adc_data_7 1 1 3 400 620 NJ 620 1390
preplace netloc axi_ad7606x_adc_enable_0 1 1 3 550 470 NJ 470 1280
preplace netloc axi_ad7606x_adc_enable_1 1 1 3 540 480 NJ 480 1290
preplace netloc axi_ad7606x_adc_enable_2 1 1 3 530 490 NJ 490 1420
preplace netloc axi_ad7606x_adc_enable_3 1 1 3 520 500 NJ 500 1430
preplace netloc axi_ad7606x_adc_enable_4 1 1 3 510 510 NJ 510 1440
preplace netloc axi_ad7606x_adc_enable_5 1 1 3 500 520 NJ 520 1450
preplace netloc axi_ad7606x_adc_enable_6 1 1 3 490 530 NJ 530 1460
preplace netloc axi_ad7606x_adc_enable_7 1 1 3 380 650 NJ 650 1400
preplace netloc axi_ad7606x_adc_reset 1 1 3 370 660 NJ 660 1410
preplace netloc axi_ad7606x_adc_valid 1 1 3 390 640 NJ 640 1380
preplace netloc axi_ad7606x_dma_irq 1 3 1 1480 1190n
preplace netloc axi_ad7606x_rx_cs_n 1 3 4 NJ 720 NJ 720 NJ 720 NJ
preplace netloc axi_ad7606x_rx_db_o 1 3 4 NJ 740 NJ 740 NJ 740 NJ
preplace netloc axi_ad7606x_rx_db_t 1 3 4 NJ 760 NJ 760 NJ 760 NJ
preplace netloc axi_ad7606x_rx_rd_n 1 3 4 NJ 780 NJ 780 NJ 780 NJ
preplace netloc axi_ad7606x_rx_wr_n 1 3 4 NJ 800 NJ 800 NJ 800 NJ
preplace netloc axi_hdmi_clkgen_clk_0 1 3 2 1370 1950 1970J
preplace netloc axi_hdmi_core_hdmi_16_data 1 5 2 NJ 2030 NJ
preplace netloc axi_hdmi_core_hdmi_16_data_e 1 5 2 NJ 2010 NJ
preplace netloc axi_hdmi_core_hdmi_16_hsync 1 5 2 NJ 1970 NJ
preplace netloc axi_hdmi_core_hdmi_16_vsync 1 5 2 NJ 1990 NJ
preplace netloc axi_hdmi_core_hdmi_out_clk 1 5 2 NJ 1950 NJ
preplace netloc axi_hdmi_dma_irq 1 3 1 1500 1230n
preplace netloc axi_iic_fmc_iic2intc_irpt 1 3 3 1570 1290 NJ 1290 2560
preplace netloc axi_iic_main_iic2intc_irpt 1 3 2 1540 1300 1850
preplace netloc axi_spdif_tx_core_spdif_tx_o 1 4 3 NJ 2100 NJ 2100 NJ
preplace netloc axi_sysid_0_rom_addr 1 1 3 550 3370 NJ 3370 1280
preplace netloc gpio_i_1 1 0 6 NJ 2520 NJ 2520 960J 2420 1530J 2210 NJ 2210 2460
preplace netloc iic_mux_scl_i_1 1 0 5 NJ 1860 NJ 1860 NJ 1860 1370J 1920 1900J
preplace netloc iic_mux_sda_i_1 1 0 5 NJ 1880 NJ 1880 910J 1930 NJ 1930 1930J
preplace netloc otg_vbusoc_1 1 0 2 NJ 3450 NJ
preplace netloc rom_sys_0_rom_data 1 2 1 870 3260n
preplace netloc rx_busy_1 1 0 3 NJ 930 NJ 930 NJ
preplace netloc rx_db_i_1 1 0 3 NJ 910 NJ 910 NJ
preplace netloc rx_first_data_1 1 0 3 NJ 950 NJ 950 NJ
preplace netloc spi0_clk_i_1 1 0 6 NJ 2540 410J 2530 970J 2520 NJ 2520 NJ 2520 2470
preplace netloc spi0_csn_i_1 1 0 6 NJ 3390 NJ 3390 NJ 3390 NJ 3390 NJ 3390 2500
preplace netloc spi0_sdi_i_1 1 0 6 NJ 3510 NJ 3510 870J 3460 1420J 3410 NJ 3410 2530
preplace netloc spi0_sdo_i_1 1 0 6 NJ 3560 NJ 3560 NJ 3560 NJ 3560 1860J 3580 2550
preplace netloc spi1_clk_i_1 1 0 6 NJ 3580 NJ 3580 NJ 3580 NJ 3580 1850J 3590 2460
preplace netloc spi1_csn_i_1 1 0 6 NJ 3600 NJ 3600 NJ 3600 NJ 3600 NJ 3600 2490
preplace netloc spi1_sdi_i_1 1 0 6 NJ 3620 430J 3610 NJ 3610 NJ 3610 NJ 3610 2520
preplace netloc spi1_sdo_i_1 1 0 6 NJ 3640 550J 3620 NJ 3620 NJ 3620 NJ 3620 2540
preplace netloc sys_200m_clk 1 2 4 980 3640 NJ 3640 NJ 3640 2590
preplace netloc sys_200m_reset 1 6 1 N 3340
preplace netloc sys_200m_resetn 1 6 1 N 3380
preplace netloc sys_audio_clkgen_clk_out1 1 3 4 1490 3630 NJ 3630 2570J 3570 2930
preplace netloc sys_concat_intc_dout 1 4 1 1950 1080n
preplace netloc sys_cpu_clk 1 0 6 20 3180 530 2550 950 2430 1520 1960 1900 3420 2450
preplace netloc sys_cpu_reset 1 1 1 N 3290
preplace netloc sys_cpu_resetn 1 1 5 490 3330 930 2440 1540 1970 1890 3650 2580
preplace netloc sys_i2c_mixer_downstream_scl_O 1 5 2 NJ 1370 NJ
preplace netloc sys_i2c_mixer_downstream_scl_T 1 5 2 NJ 1350 NJ
preplace netloc sys_i2c_mixer_downstream_sda_O 1 5 2 NJ 1410 NJ
preplace netloc sys_i2c_mixer_downstream_sda_T 1 5 2 NJ 1390 NJ
preplace netloc sys_logic_inv_Res 1 2 4 NJ 3450 1400J 3400 NJ 3400 2470
preplace netloc sys_ps7_FCLK_RESET0_N 1 0 6 30 3190 380J 3380 NJ 3380 NJ 3380 NJ 3380 2440
preplace netloc sys_ps7_FCLK_RESET1_N 1 5 1 N 3320
preplace netloc sys_ps7_GPIO_O 1 5 2 NJ 2660 NJ
preplace netloc sys_ps7_GPIO_T 1 5 2 NJ 2680 NJ
preplace netloc sys_ps7_SPI0_MOSI_O 1 5 2 NJ 2820 NJ
preplace netloc sys_ps7_SPI0_SCLK_O 1 5 2 NJ 2780 NJ
preplace netloc sys_ps7_SPI0_SS1_O 1 5 2 NJ 2900 NJ
preplace netloc sys_ps7_SPI0_SS2_O 1 5 2 NJ 2920 NJ
preplace netloc sys_ps7_SPI0_SS_O 1 5 2 NJ 2880 NJ
preplace netloc sys_ps7_SPI1_MOSI_O 1 5 2 NJ 3020 NJ
preplace netloc sys_ps7_SPI1_SCLK_O 1 5 2 NJ 2980 NJ
preplace netloc sys_ps7_SPI1_SS1_O 1 5 2 NJ 3100 NJ
preplace netloc sys_ps7_SPI1_SS2_O 1 5 2 NJ 3120 NJ
preplace netloc sys_ps7_SPI1_SS_O 1 5 2 NJ 3080 NJ
preplace netloc S00_AXI_1 1 1 5 550 2540 NJ 2540 NJ 2540 NJ 2540 2510
preplace netloc S00_AXI_2 1 3 1 1510 1500n
preplace netloc S00_AXI_3 1 3 1 1530 1440n
preplace netloc ad7606x_adc_pack_packed_fifo_wr 1 2 1 980 210n
preplace netloc axi_gp0_interconnect_M00_AXI 1 2 2 880 1580 1490J
preplace netloc axi_gp0_interconnect_M01_AXI 1 2 1 880 2120n
preplace netloc axi_gp0_interconnect_M02_AXI 1 2 1 910 2080n
preplace netloc axi_gp0_interconnect_M03_AXI 1 2 1 890 1640n
preplace netloc axi_gp0_interconnect_M04_AXI 1 2 3 920 1940 NJ 1940 NJ
preplace netloc axi_gp0_interconnect_M05_AXI 1 2 2 NJ 2200 1530
preplace netloc axi_gp0_interconnect_M06_AXI 1 2 2 NJ 2220 1300
preplace netloc axi_gp0_interconnect_M07_AXI 1 2 3 890J 2450 1370J 2510 1870
preplace netloc axi_gp0_interconnect_M08_AXI 1 2 1 870 890n
preplace netloc axi_gp0_interconnect_M09_AXI 1 2 1 900 1380n
preplace netloc axi_gp0_interconnect_M10_AXI 1 2 3 870 3170 1420J 3370 1880J
preplace netloc axi_hdmi_dma_m_axis 1 3 2 NJ 1680 1980
preplace netloc axi_hp0_interconnect_M00_AXI 1 4 1 1960 1560n
preplace netloc axi_hp1_interconnect_M00_AXI 1 4 1 1940 1800n
preplace netloc axi_i2s_adi_dma_req_rx 1 4 1 1920 2340n
preplace netloc axi_i2s_adi_dma_req_tx 1 4 1 1910 2360n
preplace netloc axi_i2s_adi_i2s 1 4 3 NJ 2380 NJ 2380 NJ
preplace netloc axi_iic_fmc_IIC 1 5 2 NJ 3710 NJ
preplace netloc axi_iic_main_IIC 1 4 1 N 1360
preplace netloc axi_spdif_tx_core_dma_req 1 4 1 1930 2080n
preplace netloc sys_ps7_DDR 1 5 2 NJ 2700 NJ
preplace netloc sys_ps7_DMA0_ACK 1 3 3 1550 2560 NJ 2560 2450
preplace netloc sys_ps7_DMA1_ACK 1 3 3 1560 2550 NJ 2550 2480
preplace netloc sys_ps7_DMA2_ACK 1 3 3 1570 2530 NJ 2530 2440
preplace netloc sys_ps7_FIXED_IO 1 5 2 NJ 2720 NJ
levelinfo -pg 1 0 200 710 1130 1710 2210 2760 2950
pagesize -pg 1 -db -bbox -sgen -180 0 3130 3800
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_system()

cr_bd_system ""
set_property REGISTERED_WITH_MANAGER "1" [get_files system.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files system.bd ] 

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2025} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2025" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2025} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2025" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.routable_nets" -value "1" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7z020clg484-1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
